### ISSUE TITLE
Project jspm psackage not updated for Aurelia 0.15.0 breaking changes

### ISSUE THREAD

**Issue by KarlDirck** [PWKad/aurelia-bs-modal#22]
There was a breaking change in Aurelia 0.15.0 where globalizeResources method was renamed to globalResources.
Error:
Unhandled promise rejection TypeError: config.globalResources is not a function
    at y.configure (http://localhost:9000/app/jspm_packages/github/pwkad/aurelia-bs-modal@0.2.3/index.js:6:12)
    at http://localhost:9000/app/jspm_packages/github/aurelia/framework@0.13.4/aurelia-framework.js:25:34
    at run (http://localhost:9000/app/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:9000/app/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:9000/app/jspm_packages/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:9000/app/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:9000/app/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:27:7)

**Comment by alexmills** [comment]
I'm having the same problem, what's the best way to solve this issue? I've changed these lines to get it working in the interim

``` javascript
function configure(config) {
    config.globalizeResources('./modal');
    config.globalizeResources('./modal-header');
    config.globalizeResources('./modal-body');
    config.globalizeResources('./modal-footer');
    config.globalizeResources('./au-button');
  }
```
