### ISSUE TITLE
build Error: Cannot find module 'object.assign'

### ISSUE THREAD

**Issue by atsu85** [PWKad/aurelia-bs-modal#31]
build fails with

> Error: Cannot find module 'object.assign'

**Comment by atsu85** [comment]
Just in case, i'll provide some more information to reproduce the problem:

OS: Windows 8.1
node: v0.12.4

Output of `gulp build`:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'object.assign'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\tmp\proj\cloned\aurelia\aurelia-bs-modal\build\tasks\build.js:6:31)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by atsu85** [comment]
to resolve this issue, please merge my pull request https://github.com/PWKad/aurelia-bs-modal/pull/35 and run `gulp build` to update dist folder
